# Deklarasikan gambar di bawah line ini, menggunakan pernyataan image.
image dream = "images/BG/dream.png"
image mc bedroom = "images/BG/bedroom.png"
image kampus = "images/BG/kampus.png"
image depan kampus = "images/BG/depan_kampus_resize.jpg"
image kelas = "images/BG/kelas.jpg"
image cafe = "images/BG/cafe_resize.jpg"
image kantin = "images/BG/kantin_resize.jpg"
image awan = "images/BG/transi.png"
image kana awal = "images/CG/kana_awal_resize.png"
image mini game = "images/background.png"
image monas temporary = "images/BG/monas_temp.jpg"
image mall temp = "images/BG/mall-temp.jpg"
image depan kosan = "images/BG/depan-kosan.jpg"
image white = Solid("#FFFFFF")
image pia tabrakan normal = "images/CG/pia_tabrakan_normal.png"
image pia tabrakan ngomong = "images/CG/pia_tabrakan_ngomong.png"
